In [4]:
pip install -q tensorflow

In [5]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.11/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [6]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [8]:
string,number,floating

(<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.566999912261963>)

In [9]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [11]:
tf.rank(rank1_tensor),tf.rank(rank2_tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

### Reshape

In [12]:
rank2_tensor.shape

TensorShape([2, 2])

In [13]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place


# The numer of elements in the reshaped tensor MUST match the number in the original

In [14]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Slicing

In [15]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [18]:
three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3
print("::::::::::")

row1 = tensor[0]  # selects the first row
print(row1)
print("::::::::::")

column1 = tensor[:, 0]  # selects the first column
print(column1)
print("::::::::::")

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)
print("::::::::::")

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
::::::::::
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
::::::::::
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
::::::::::
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
::::::::::
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
